[package]
name = "advent_of_code_2023"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
ndarray = "0.16.1"
nom = { version = "8.0.0", features = ["alloc"] }
num = "0.4.3"
regex = "1.11.1"

[lints.rust]
unsafe_code = "forbid"
